---
- name: Create temporary file for output
  tempfile:
    state: file
    suffix: temp
  register: temporary_file_path


- name: Collect dump
  become: true
  shell: "timeout {{ tcpgraph__duration }} tcpdump {{ tcpgraph__args }} | {{ tcpgraph__filter }} > {{ temporary_file_path }}"

- name: Download dump from remote host
  fetch:
    src: "{{ temporary_file_path }}"
    dst: "~/.tcpgraph"

- name: Remove dump on remote host
  file:
    path: "{{ temporary_file_path }}"
    state: absent
